directories:
  - "/Users/mhanheide/Library/CloudStorage/OneDrive-UniversityofLincoln/Attachments"
  - "/Users/mhanheide/Library/CloudStorage/OneDrive-UniversityofLincoln/Emails"
  - "/Users/mhanheide/Library/CloudStorage/OneDrive-UniversityofLincoln/Reviews"
  - "/Users/mhanheide/Library/CloudStorage/OneDrive-UniversityofLincoln/letters"
  - "/Users/mhanheide/Library/CloudStorage/OneDrive-SharedLibraries-UniversityofLincoln/UoL Academic Board - General/2024-25"
  - "/Users/mhanheide/Downloads"
  - "/Users/mhanheide/Desktop"
  
  # Add more directories as needed

# File extensions to process
file_extensions:
  - ".txt"
  - ".md"
  - ".pdf"
  - ".docx"
  - ".pptx"
  - ".xlsx"
  - ".html"
  - ".htm"
  - ".rtf"

# Qdrant configuration
qdrant:
  host: "localhost"
  port: 6333
  collection_name: "rag_documents"
  vector_size: 384  # Default for all-MiniLM-L6-v2

# Embedding model configuration
embedding:
  model_name: "all-MiniLM-L6-v2"  # Fast and good quality
  chunk_size: 1024  # Characters per chunk
  chunk_overlap: 200  # Overlap between chunks

# Processing configuration
processing:
  max_file_size_mb: 5  # Skip files larger than this
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - ".git/*"
    - "__pycache__/*"
    - "*.pyc"
    - ".venv/*"
    - "*.DS_Store"

  # When files are deleted, should we delete embeddings or mark as deleted?
  delete_embeddings_on_file_deletion: false  # Set to true to delete, false to mark as deleted

# Memory optimization settings
memory:
  chunk_batch_size: 50  # Process document chunks in batches
  hash_loading_batch_size: 5000  # Load file hashes in batches
  unload_model_after_idle_minutes: 30  # Unload embedding model after idle time
  force_gc_after_operations: 100  # Force garbage collection after N operations

# Logging
logging:
  level: "WARNING"  # DEBUG, INFO, WARNING, ERROR
  file: "rag_monitor.log"
  mcp_logfile: "/tmp/mcp_server.log"
