name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmagic1 libmagic-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Check formatting with black
      run: |
        black --check --diff .

    - name: Lint with flake8
      run: |
        flake8 rag_file_monitor/ mcp_server.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 rag_file_monitor/ mcp_server.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Type check with mypy
      run: |
        mypy rag_file_monitor/ --ignore-missing-imports --no-strict-optional
      continue-on-error: true

    - name: Security scan with bandit
      run: |
        bandit -r rag_file_monitor/ mcp_server.py -ll
      continue-on-error: true

    - name: Check dependencies for security issues
      run: |
        pip freeze | safety check --stdin
      continue-on-error: true
